# Generated by Django 4.2.7 on 2025-03-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('playlist_name', models.CharField(max_length=50)),
                ('playlist_public', models.CharField(max_length=7)),
                ('collaborative', models.BooleanField()),
                ('song', models.CharField(max_length=50)),
            ],
        ),
    ]
