# Generated by Django 4.2.7 on 2025-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrec', '0004_remove_song_associated_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='collaborative',
            field=models.CharField(max_length=3),
        ),
    ]
