# Generated by Django 4.2.7 on 2025-03-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrec', '0006_alter_playlist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
