# Generated by Django 4.2.7 on 2025-03-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrec', '0007_remove_playlist_song_playlist_playlist_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
