# Generated by Django 4.2.7 on 2025-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrec', '0010_alter_chart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
