# Generated by Django 4.2.7 on 2025-03-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrec', '0011_chart_chart_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
